// program.jsx — the 7-day guided program, questions taken from the ebook
// "Mi diario · 7 días para salir de la neblina mental y recuperar la calma".

const DT_PROGRAM = [
  {
    n: 1, title: 'Vaciá tu mente', minutes: 10,
    blocks: [
      { t: 'section', label: 'Escritura libre' },
      { t: 'text', id: 'd1_libre', big: true,
        q: 'Escribí TODO lo que te está dando vueltas en la cabeza',
        hint: 'Lo que te preocupa, lo que te molesta, lo que sentís que “deberías” hacer, lo que te da culpa, lo que te estresa, lo que querés pero no te animás. Sin parar, sin corregir.',
        placeholder: 'Escribí sin parar…' },
      { t: 'section', label: 'Separá lo real de lo inventado' },
      { t: 'text', id: 'd1_control',
        q: '¿Qué de todo eso SÍ podés hacer algo al respecto?',
        placeholder: 'Está en mi control…' },
      { t: 'text', id: 'd1_nocontrol',
        q: '¿Qué NO podés controlar, o es un juicio y no un hecho?',
        placeholder: 'No lo controlo…' },
      { t: 'section', label: 'Elegí una acción' },
      { t: 'text', id: 'd1_accion',
        q: 'La cosa que voy a resolver es:',
        placeholder: 'Una sola.' },
      { t: 'text', id: 'd1_cuando',
        q: 'Voy a hacerlo:',
        hint: 'Cuándo exactamente.',
        placeholder: 'Hoy a las…' },
    ],
  },
  {
    n: 2, title: 'De la neblina al plan', minutes: 10,
    blocks: [
      { t: 'section', label: 'Priorizá según importancia real' },
      { t: 'text', id: 'd2_urgente',
        q: 'URGENTE Y NECESARIO',
        hint: 'Cosas que si no las hacés, hay consecuencias reales.',
        placeholder: 'Esta semana sí o sí…' },
      { t: 'text', id: 'd2_importante',
        q: 'IMPORTANTE PERO NO URGENTE',
        hint: 'Importan pero no tienen fecha límite inmediata.',
        placeholder: 'Puede esperar un poco…' },
      { t: 'text', id: 'd2_gustaria',
        q: 'ME GUSTARÍA PERO NO ES PRIORIDAD',
        hint: 'Ni urgentes ni críticas ahora.',
        placeholder: 'Para después…' },
      { t: 'section', label: 'Tu plan de esta semana · máximo 3' },
      { t: 'group', label: 'Cosa 1', fields: [
        { id: 'd2_c1_que', q: '¿Qué tengo que hacer?' },
        { id: 'd2_c1_cuando', q: '¿Cuándo exactamente? (día y hora)' },
        { id: 'd2_c1_tiempo', q: '¿Cuánto tiempo me va a llevar?' },
      ] },
      { t: 'group', label: 'Cosa 2', fields: [
        { id: 'd2_c2_que', q: '¿Qué tengo que hacer?' },
        { id: 'd2_c2_cuando', q: '¿Cuándo exactamente? (día y hora)' },
        { id: 'd2_c2_tiempo', q: '¿Cuánto tiempo me va a llevar?' },
      ] },
      { t: 'group', label: 'Cosa 3', fields: [
        { id: 'd2_c3_que', q: '¿Qué tengo que hacer?' },
        { id: 'd2_c3_cuando', q: '¿Cuándo exactamente? (día y hora)' },
        { id: 'd2_c3_tiempo', q: '¿Cuánto tiempo me va a llevar?' },
      ] },
    ],
  },
  {
    n: 3, title: 'Lo que querés vs. lo que “deberías” querer', minutes: 10,
    blocks: [
      { t: 'section', label: 'Tu lista de “deberías”' },
      { t: 'text', id: 'd3_madre', q: 'Como madre, debería…', placeholder: 'Rápido, sin pensar demasiado.' },
      { t: 'text', id: 'd3_mujer', q: 'Como mujer, debería…' },
      { t: 'text', id: 'd3_casa', q: 'En mi casa, debería…' },
      { t: 'text', id: 'd3_pareja', q: 'Con mi pareja o familia, debería…' },
      { t: 'section', label: 'Lo que REALMENTE querés' },
      { t: 'text', id: 'd3_tipo_madre', q: '¿Qué tipo de madre querés ser?',
        hint: 'No lo que te dijeron que deberías ser.' },
      { t: 'text', id: 'd3_tiempo_libre', q: '¿Cómo querés pasar tu tiempo libre?' },
      { t: 'text', id: 'd3_feliz', q: '¿Qué cosas te hacen feliz que tal vez “no deberías” querer?' },
      { t: 'text', id: 'd3_sin_juicio', q: 'Si nadie te juzgara, ¿qué cambiarías de tu vida?' },
      { t: 'text', id: 'd3_extranas', q: '¿Qué extrañás de vos misma?' },
      { t: 'section', label: 'Encontrá los conflictos' },
      { t: 'text', id: 'd3_conflictos', big: true,
        q: 'Escribí 3 conflictos que encontraste',
        hint: 'Dónde tu “debería” y tu “quiero” se contradicen.',
        placeholder: '1.\n2.\n3.' },
    ],
  },
  {
    n: 4, title: 'Calma en medio del caos', minutes: 10,
    blocks: [
      { t: 'section', label: 'Identificá tus momentos automáticos' },
      { t: 'check', id: 'd4_momentos',
        q: '¿Cuáles de estos hacés todos los días en modo automático?',
        options: ['Preparar el desayuno', 'Bañarte', 'Lavar los platos', 'Lavar o doblar ropa',
          'Ir al baño', 'Tomar agua, café o mate', 'Caminar de una habitación a otra',
          'Esperar que se cocine algo', 'Manejar o viajar en transporte', 'Acostar a los chicos'] },
      { t: 'text', id: 'd4_otros', q: '¿Otros momentos que quieras agregar?' },
      { t: 'section', label: 'Elegí 3 momentos para transformar' },
      { t: 'text', id: 'd4_m1', q: 'Momento 1' },
      { t: 'text', id: 'd4_m2', q: 'Momento 2' },
      { t: 'text', id: 'd4_m3', q: 'Momento 3' },
    ],
  },
  {
    n: 5, title: 'Decir que no sin morir de culpa', minutes: 10,
    blocks: [
      { t: 'section', label: 'Tus “síes” por culpa' },
      { t: 'text', id: 'd5_dije_si', big: true,
        q: '¿A qué dijiste que sí últimamente sin querer hacerlo?',
        placeholder: 'Dije que sí a…' },
      { t: 'check', id: 'd5_por_que',
        q: '¿Por qué dije que sí si no quería?',
        options: ['Porque si decía que no, iban a pensar que soy egoísta',
          'Porque “debería” poder hacerlo',
          'Porque no quería quedar mal',
          'Porque me da culpa decepcionar',
          'Porque me pidieron de una forma que no pude negarme',
          'Porque siempre lo hago, ya es esperado de mí'] },
      { t: 'text', id: 'd5_otra_razon', q: '¿Otra razón?' },
      { t: 'section', label: 'El costo real de esos “síes”' },
      { t: 'group', label: 'Cuando dije que sí, sacrifiqué…', fields: [
        { id: 'd5_tiempo', q: 'Mi tiempo para:' },
        { id: 'd5_energia', q: 'Mi energía para:' },
        { id: 'd5_calma', q: 'Mi calma porque:' },
      ] },
      { t: 'section', label: 'Tu nueva frase de poder' },
      { t: 'text', id: 'd5_proxima',
        q: 'La próxima vez que me pidan…',
        placeholder: 'Elegí UNA cosa de tu lista.' },
      { t: 'text', id: 'd5_frase',
        q: 'Mi frase va a ser:',
        hint: '“Ahora no puedo, pero gracias por pensar en mí” · “No me da el tiempo esta vez” · “Te agradezco, pero voy a tener que pasar” · “No puedo comprometerme con eso ahora” · “Esta semana estoy llena, no puedo sumar nada más”',
        placeholder: 'Escribila con tus palabras y decila en voz alta 3 veces.' },
    ],
  },
  {
    n: 6, title: 'Nombrar lo que sentís', minutes: 10,
    blocks: [
      { t: 'section', label: '¿Cómo te sentís ahora?' },
      { t: 'check', id: 'd6_cuerpo',
        q: '¿Qué sentís físicamente?',
        hint: 'Cerrá los ojos, respirá 3 veces profundo y prestá atención a tu cuerpo.',
        options: ['Tensión en los hombros o el cuello', 'Nudo en el estómago',
          'Presión en el pecho', 'Cansancio en todo el cuerpo',
          'Inquietud, necesidad de moverme', 'Vacío o adormecimiento'] },
      { t: 'text', id: 'd6_cuerpo_otro', q: '¿Otra cosa?' },
      { t: 'radio', id: 'd6_primaria',
        q: '¿Cuál emoción primaria resuena más?',
        options: ['Enojo', 'Tristeza', 'Miedo', 'Alegría'] },
      { t: 'check', id: 'd6_especifica', dependsOn: 'd6_primaria',
        q: '¿Cuál específicamente?',
        optionsBy: {
          'Enojo': ['Frustración', 'Irritación', 'Resentimiento', 'Rabia', 'Indignación'],
          'Tristeza': ['Melancolía', 'Desilusión', 'Soledad', 'Nostalgia', 'Desesperanza'],
          'Miedo': ['Ansiedad', 'Preocupación', 'Inseguridad', 'Pánico', 'Nerviosismo'],
          'Alegría': ['Satisfacción', 'Alivio', 'Entusiasmo', 'Gratitud', 'Paz'],
        } },
      { t: 'section', label: '¿De dónde viene?' },
      { t: 'text', id: 'd6_porque', big: true,
        q: 'Me siento así porque:',
        placeholder: 'Elegí la emoción más fuerte y escribí de dónde viene.' },
      { t: 'radio', id: 'd6_hace_cuanto',
        q: '¿Hace cuánto que venís sintiendo esto?',
        options: ['Hoy', 'Esta semana', 'Este mes', 'Más tiempo'] },
      { t: 'radio', id: 'd6_origen',
        q: 'Esta emoción es:',
        options: ['Por algo específico que pasó', 'Por algo que está pasando ahora',
          'Por algo que PODRÍA pasar', 'Viene de algo viejo que nunca procesé',
          'No sé, simplemente la siento'] },
      { t: 'check', id: 'd6_necesito',
        q: '¿Qué necesitás para procesar esta emoción?',
        options: ['Llorar', 'Hablar con alguien', 'Estar sola', 'Moverme: caminar, bailar',
          'Escribir más sobre esto', 'Resolver algo concreto', 'Solo validar que la siento'] },
      { t: 'section', label: 'Validá lo que sentís' },
      { t: 'text', id: 'd6_valido', big: true,
        q: 'Tiene sentido que me sienta… porque…',
        hint: 'Es válido sentir esto. No necesito arreglarlo ahora. Solo necesito reconocerlo.',
        placeholder: 'Tiene sentido que me sienta…' },
    ],
  },
  {
    n: 7, title: 'Lo que llevás (y lo que sigue)', minutes: 15,
    blocks: [
      { t: 'section', label: 'Mirá hacia atrás' },
      { t: 'text', id: 'd7_r1', q: 'Día 1 · ¿Qué vaciaste de tu mente?',
        hint: '¿Cómo te sentías antes de escribir ese día? ¿Cómo te sentís ahora?' },
      { t: 'text', id: 'd7_r2', q: 'Día 2 · ¿Pudiste hacer las 3 cosas que priorizaste?',
        hint: 'Si hiciste al menos una, eso cuenta.' },
      { t: 'text', id: 'd7_r3', q: 'Día 3 · ¿Qué descubriste sobre tus “deberías” vs. lo que realmente querés?' },
      { t: 'text', id: 'd7_r4', q: 'Día 4 · ¿Pudiste estar presente en esos momentos? ¿Cómo se sintió?' },
      { t: 'text', id: 'd7_r5', q: 'Día 5 · ¿Dijiste que no a algo? ¿Cómo te sentiste después?' },
      { t: 'text', id: 'd7_r6', q: 'Día 6 · ¿Pudiste nombrar lo que sentías?' },
      { t: 'section', label: '¿Qué cambió?' },
      { t: 'radio', id: 'd7_mente',
        q: '¿Cómo describirías tu mente hoy vs. el día 1?',
        options: ['Más despejada', 'Un poco más clara',
          'Todavía confusa pero menos agobiante', 'Igual de caótica'] },
      { t: 'radio', id: 'd7_control',
        q: '¿Te sentís más en control de tu día?',
        options: ['Sí', 'A veces', 'Todavía no pero veo el camino', 'No'] },
      { t: 'check', id: 'd7_emociones',
        q: '¿Cambió algo en cómo te relacionás con tus emociones?',
        options: ['Las identifico más rápido', 'Las juzgo menos', 'Las valido más',
          'Todavía cuesta pero estoy aprendiendo'] },
      { t: 'text', id: 'd7_valioso', big: true,
        q: '¿Qué fue lo MÁS valioso que te llevás de estos 7 días?' },
      { t: 'section', label: 'Tu plan para seguir' },
      { t: 'check', id: 'd7_seguir',
        q: 'Elegí 2 cosas que querés seguir haciendo',
        options: ['Vaciar mi mente cuando esté abrumada',
          'Priorizar solo 3 cosas urgentes por semana',
          'Revisar mis “deberías” cuando sienta culpa',
          'Practicar presencia en momentos cotidianos',
          'Decir que no sin explicaciones infinitas',
          'Nombrar y validar mis emociones'] },
    ],
  },
];

function dtProgramDay(day) {
  if (!day) return null;
  return DT_PROGRAM[(day - 1) % DT_PROGRAM.length] || null;
}

Object.assign(window, { DT_PROGRAM, dtProgramDay });
